spring:
    profiles:
        active: prod
    social:
        # see https://developers.google.com/+/web/signin/server-side-flow#step_1_create_a_client_id_and_client_secret
        google:
            clientId: 504200167671-9s0scgbdulvm4u9rdgq95qa1vqk3uam4.apps.googleusercontent.com
            clientSecret: 9ZQk5AaBnKTxkbb19zz6WSyr

        # see https://developers.facebook.com/docs/facebook-login/v2.2
        facebook:
            clientId: 912472022199215
            clientSecret: 9a551587d44a6505291cab3c1a33ead5

        # see https://apps.twitter.com/app/
        twitter:
            clientId: X1S2BH04CdYXYtHfTG6gGa5C7
            clientSecret: 3FOSZfivHHQL9OAjV3ybU5ErLZkftV5BL4xbbeoCP1GjmvSP2D
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false

    mail:
        host: smtp.gmail.com
        port: 587
        username: otchi.dev@gmail.com
        password: ihcto77$L23
        properties:
            mail:
               smtp:
                   ssl: true
                   auth: true
                   socketFactory:
                       class: javax.net.ssl.SSLSocketFactory
                       fallback: false
                       port: 465

liquibase:
    contexts: prod
    change-log: classpath:/database/db.changelog-master.xml

amazon:
    aws:
        access-key-id: AKIAJFCC3VEOC7MARD4A
        access-key-secret: 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
        availabilty-zone : eu-central-1
    s3:
      default-bucket: otchi
      url: s3.amazonaws.com
otchi:
   stomp:
      relayHost: squirrel.rmq.cloudamqp.com
      relayPort: 61613
      clientLogin: dqgowlzx
      clientPasscode: sb6B1-4vOgGCNlUtYPpDwrG7KBNvlxNV
      systemLogin: dqgowlzx
      systemPasscode: sb6B1-4vOgGCNlUtYPpDwrG7KBNvlxNV
      virtualHost: dqgowlzx
      relayDestinationPrefix: /topic
      appDestinationPrefix: /app
      endpoint: /socket