spring:
    profiles:
        active: prod
    social:
        # see https://developers.google.com/+/web/signin/server-side-flow#step_1_create_a_client_id_and_client_secret
        google:
            clientId: 504200167671-9s0scgbdulvm4u9rdgq95qa1vqk3uam4.apps.googleusercontent.com
            clientSecret: 9ZQk5AaBnKTxkbb19zz6WSyr

        # see https://developers.facebook.com/docs/facebook-login/v2.2
        facebook:
            clientId: 381879212199335
            clientSecret: 0fa1419fc5c45820c094822a0222147a

        # see https://apps.twitter.com/app/
        twitter:
            clientId: X1S2BH04CdYXYtHfTG6gGa5C7
            clientSecret: 3FOSZfivHHQL9OAjV3ybU5ErLZkftV5BL4xbbeoCP1GjmvSP2D
    datasource:
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
        url: ${JDBC_DATABASE_URL}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        database: POSTGRESQL
        openInView: true
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false

    mail:
        host: mail.gandi.net
        port: 25
        username: noreply@otchi.io
        password: ihcto77$L23
liquibase:
    contexts: prod
    change-log: classpath:/database/db.changelog-master.xml

amazon:
    aws:
        access-key-id: AKIAJFCC3VEOC7MARD4A
        access-key-secret: 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
        availabilty-zone : eu-central-1
    s3:
      default-bucket: otchi
      url: s3.amazonaws.com
otchi:
   url: http://www.otchi.io
   stomp:
      relayHost: squirrel.rmq.cloudamqp.com
      relayPort: 61613
      clientLogin: dqgowlzx
      clientPasscode: sb6B1-4vOgGCNlUtYPpDwrG7KBNvlxNV
      systemLogin: dqgowlzx
      systemPasscode: sb6B1-4vOgGCNlUtYPpDwrG7KBNvlxNV
      virtualHost: dqgowlzx
      relayDestinationPrefix: /topic
      appDestinationPrefix: /app
      endpoint: /socket
