INSERT INTO USER(ID,EMAIL,PASSWORD,FIRST_NAME,LAST_NAME,ACTIVATED)
        VALUES(1,'zeroual.abde@gmail.com','$2a$10$9m.et2mcPSzA4RdS1AOGPemNLOCerTkyEC99BUdqMSNL.4F9HUtbW','Abdellah','ZEROUAL',1);

INSERT INTO USER(ID,EMAIL,PASSWORD,FIRST_NAME,LAST_NAME,ACTIVATED)
        VALUES(2,'m.amine.jabri@gmail.com','$2a$10$2msNJre9jMfIKWxq/tXPP.F2GR6MRP3Hu0pscFOpYeOQzSqsrj2TO','Amin','JABRI',1);

INSERT INTO USER(ID,EMAIL,PASSWORD,FIRST_NAME,LAST_NAME,ACTIVATED)
        VALUES(3,'mr.jaifar@gmail.com','$2a$10$ir99IGmrvfFc90qloVGJr.XY03r2rFnsvhNcp8OH40HEClM7KSbeO','Reda','JAIFAR',1);